workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter analyze
        script: |
          flutter analyze
        ignore_failure: true
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build Debug APK
        script: |
          flutter build apk --debug \
            --dart-define=SUPABASE_URL=${SUPABASE_URL} \
            --dart-define=SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    artifacts:
      - build/**/outputs/**/*.apk
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - developer@specialone.com
        notify:
          success: true
          failure: true

  release-apk-build:
    name: Build Release APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*'
          include: true
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter analyze
        script: |
          flutter analyze
        ignore_failure: true
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build Release APK
        script: |
          flutter build apk --release \
            --dart-define=SUPABASE_URL=${SUPABASE_URL} \
            --dart-define=SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    artifacts:
      - build/**/outputs/**/*.apk
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - admin@specialone.com
        notify:
          success: true
          failure: true
