name: special_one_student
publish_to: 'none'
description: Student attendance app for Ahmed Sami – Special One
version: 0.0.1+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.10

  # UI & Navigation
  go_router: ^12.1.3
  flutter_screenutil: ^5.9.0
  qr_flutter: ^4.1.0

  # Localization
  intl: ^0.20.2

  # Utilities
  shared_preferences: ^2.2.3
  image_picker: ^1.0.4
  path_provider: ^2.1.3
  url_launcher: ^6.2.2
  cupertino_icons: ^1.0.2
  
  # Supabase
  supabase_flutter: ^2.6.0
  # Networking & local database & notifications
  http: ^1.2.1
  sqflite: ^2.3.3
  path: ^1.9.0
  flutter_local_notifications: ^17.2.3
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - lib/lang/
    - assets/images/